# Generated by Django 4.0.4 on 2022-04-29 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='role',
        ),
        migrations.RemoveField(
            model_name='account',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='account',
            name='uniqueId',
        ),
    ]
