# Generated by Django 4.0.4 on 2022-04-26 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_resume_address_line1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='date_birth',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='sex',
        ),
    ]
