# Generated by Django 4.0.4 on 2022-04-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_experience_date_created_alter_experience_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='skills',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
