# Generated by Django 4.0.4 on 2022-05-06 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='companyLogo',
            field=models.ImageField(default='default-job.png', upload_to='profile_images'),
        ),
    ]
