# Generated by Django 4.0.4 on 2022-04-29 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applicants',
        ),
        migrations.DeleteModel(
            name='Employers',
        ),
        migrations.DeleteModel(
            name='JobPosting',
        ),
    ]
