# Generated by Django 4.0.4 on 2022-05-07 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_company_companylogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='companyLogo',
            field=models.ImageField(default='default-job.png', upload_to='upload_images'),
        ),
    ]
