# Generated by Django 4.0.4 on 2022-05-09 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_remove_job_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='closing_date',
        ),
        migrations.RemoveField(
            model_name='job',
            name='requirements',
        ),
    ]
