# Generated by Django 4.0.4 on 2022-04-29 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='first_name',
            field=models.CharField(default='Owner', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='last_name',
            field=models.CharField(default='Owner', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('Employer', 'Employer'), ('Applicant', 'Applicant')], default='Applicant', max_length=10),
        ),
        migrations.AddField(
            model_name='account',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='account',
            name='uniqueId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
