# Generated by Django 4.0.4 on 2022-05-05 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_account_company_account_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='address_line1',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='address_line2',
        ),
    ]
