# Generated by Django 4.0.4 on 2022-05-05 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_resume_address_line1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='experience',
        ),
    ]
