# Generated by Django 4.0.4 on 2022-05-05 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('user', '0004_remove_education_qualification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.company'),
        ),
    ]
