# Generated by Django 4.0.4 on 2022-05-05 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('user', '0005_alter_experience_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='company',
        ),
        migrations.AddField(
            model_name='resume',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.company'),
        ),
    ]
