# Generated by Django 4.0.4 on 2022-05-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_resume_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='email_confirmed',
        ),
        migrations.AddField(
            model_name='account',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
