# Generated by Django 4.0.4 on 2022-05-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_resume_email_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='project_implicit',
            field=models.FileField(blank=True, null=True, upload_to='project_implicit'),
        ),
    ]
