# Generated by Django 4.0.4 on 2022-05-09 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_resume_project_implicit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='project_implicit',
        ),
        migrations.CreateModel(
            name='ProjectImplicit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_implicit', models.FileField(blank=True, null=True, upload_to='project-implicit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
