# Generated by Django 4.0.4 on 2022-05-09 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_zoommeeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zoommeeting',
            name='interviewer',
        ),
    ]
