# Generated by Django 4.0.4 on 2022-05-09 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_zoommeeting_interviewer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZoomMeeting',
        ),
    ]
