# Generated by Django 4.0.4 on 2022-05-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_zoommeeting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZoomMeeting',
        ),
    ]
