# Generated by Django 4.0.4 on 2022-05-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_meetingzoom'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingzoom',
            name='link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
